name: API Request on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  api_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract PR Information
        id: pr_info
        run: |
          echo "::set-output name=data::'{\"title\": \"${{ github.event.pull_request.title }}\", \"number\": ${{ github.event.pull_request.number }}, \"user\": \"${{ github.event.pull_request.user.login }}\"}'"

      - name: Make API Request
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            echo "${{ steps.pr_info.outputs.data }}" > pr_data.json
            curl -X POST -H "Content-Type: application/json" --data @pr_data.json https://example.com/api/endpoint
          fi
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
