name: API Request on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  api_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract PR Information
        id: pr_info
        run: |
          echo "::set-output name=data:: |
            {
              \"title\": \"${{ github.event.pull_request.title }}\",
              \"number\": ${{ github.event.pull_request.number }},
              \"user\": \"${{ github.event.pull_request.user.login }}\"
            }"
            
      - name: Extract ticket number from PR title
        id: extract_ticket
        run: |
          TICKET_NUMBER=$(echo "${{ github.event.pull_request.title }}" | sed -nE 's/.*ticket\s*#\s*([0-9]+).*/\1/p')
          echo "::set-output name=ticket_number::${TICKET_NUMBER}"
          
      - name: Make API Request
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            curl -X POST -H "Content-Type: application/json" -d '{"user": "${{github.event.pull_request.user.login}}", "number": "${{github.event.pull_request.number}}", "ticket_number": ${{steps.extract_ticket.outputs.ticket_number}} }' https://httpdump.app/dumps/3220de01-ed9d-488e-a34f-9893a07fed60
          fi
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
