name: API Request on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  api_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract PR Information
        id: pr_info
        run: |
          echo "::set-output name=data:: |
            {
              \"title\": \"${{ github.event.pull_request.title }}\",
              \"number\": ${{ github.event.pull_request.number }},
              \"user\": \"${{ github.event.pull_request.user.login }}\"
            }"
            
      - name: Extract ticket number from PR title
        id: extract_ticket_from_title
        run: |
          TICKET_NUMBER=$(echo "${{ github.event.pull_request.title }}" | sed -nE '\d{6,9}')
          echo "::set-output name=ticket_number_from_title::${TICKET_NUMBER}"
          
      - name: Extract ticket number from PR body
        id: extract_ticket_from_body
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          TICKET_NUMBER_FROM_BODY=$(echo "$PR_BODY" | sed -nE 's|.*/Tickets/ViewTicket/([0-9]+)|\1|p')
          echo "::set-output name=ticket_number_from_body::${TICKET_NUMBER_FROM_BODY}"

      - name: Determine ticket number to submit
        id: determine_ticket_number
        run: |
          if [[ -n "${{ steps.extract_ticket_from_title.outputs.ticket_number_from_title }}" ]]; then
            echo "::set-output name=ticket_to_submit::${{ steps.extract_ticket_from_title.outputs.ticket_number_from_title }}"
          elif [[ -n "${{ steps.extract_ticket_from_body.outputs.ticket_number_from_body }}" ]]; then
            echo "::set-output name=ticket_to_submit::${{ steps.extract_ticket_from_body.outputs.ticket_number_from_body }}"
          else
            echo "::set-output name=ticket_to_submit::"
          fi
          
      - name: Make API Request
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            curl -X POST -H "Content-Type: application/json" -d '{"user": "${{github.event.pull_request.user.login}}", "number": "${{github.event.pull_request.number}}", "ticket_number": ${{steps.determine_ticket_number.outputs.ticket_to_submit}} }' https://httpdump.app/dumps/3220de01-ed9d-488e-a34f-9893a07fed60
          fi
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
